# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-03 23:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeanOfficeNumbersQueue',
            fields=[
                ('numberId', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=200)),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('faculty', models.CharField(max_length=100)),
                ('groupId', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WelfareOfficeNumbersQueue',
            fields=[
                ('numberId', models.AutoField(primary_key=True, serialize=False)),
                ('studentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deanOffice.Student')),
            ],
        ),
        migrations.AddField(
            model_name='deanofficenumbersqueue',
            name='studentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deanOffice.Student'),
        ),
    ]
